FROM alpine:latest
RUN apk --no-cache add ca-certificates
# Add everything in raftcat subdirectory that's whitelisted by .dockerignore
ADD raftcat/*
ADD raftcat.x86_64-unknown-linux-musl /bin/raftcat
EXPOSE 8080
ENTRYPOINT ["/bin/raftcat"]
